import React, { useState } from 'react';
import '../styles/FAQ.css';

function FAQ() {
  const [activeIndex, setActiveIndex] = useState(null);

  const faqs = [
    {
      question: 'What is E2E Test Generator?',
      answer: 'E2E Test Generator is a VS Code extension created by TestgenX team that helps you create end-to-end tests for web applications using Playwright. It allows you to record user interactions and automatically generates test code.'
    },
    {
      question: 'Which browsers are supported?',
      answer: 'E2E Test Generator supports all browsers that Playwright supports, including Chrome and Firefox'
    },
    {
      question: 'Does it work with Flutter web applications?',
      answer: 'Yes, E2E Test Generator has special support for Flutter web applications with custom element detection that understands Flutter-specific DOM structures.'
    },
    {
      question: 'Can I integrate the tests with my CI/CD pipeline?',
      answer: 'Absolutely! The tests generated by E2E Test Generator are standard Playwright tests that can be easily integrated into any CI/CD pipeline that supports Node.js.'
    },
    {
      question: 'Is E2E Test Generator free to use?',
      answer: 'Yes, E2E Test Generator is currently free to use during the beta period. We may introduce premium features in the future, but the core functionality will remain free.'
    },
    {
      question: 'How do I get support if I encounter issues?',
      answer: 'You can report issues on our GitHub repository or contact our support team through the VS Code Marketplace page.'
    }
  ];

  const toggleAccordion = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section className="faq" id="faq">
      <h1>Frequently Asked Questions</h1>
      <div className="faq-container">
        {faqs.map((faq, index) => (
          <div 
            className={`faq-item ${activeIndex === index ? 'active' : ''}`} 
            key={index}
          >
            <div 
              className="faq-question" 
              onClick={() => toggleAccordion(index)}
            >
              <h3>{faq.question}</h3>
              <span className="faq-icon">{activeIndex === index ? '−' : '+'}</span>
            </div>
            <div className="faq-answer">
              <p>{faq.answer}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default FAQ; 